FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY app/web/package.json ./app/web/
COPY packages/domain/package.json ./packages/domain/

RUN pnpm fetch

COPY . .

RUN pnpm i --frozen-lockfile --offline

RUN pnpm build

FROM nginx:alpine

COPY --from=builder /app/app/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]